### DISCUSSION TITLE
Browser compatibility section, browser row should be sticky

### DISCUSSION THREAD

**Discussion by vinzusama** [mdn/mdn-community#298] [Platform]
Hi everyone,

It's not something big, really, but I think it would be good that the browser row, inside the full browser compatibility table should be sticky.
In case of long (loooong) table correspondences, you rapidely find yourself with the <thead> hidden. So you have to either memorize the correspondig row of each browser, or to scroll to top than back to the line you were looking for. 

See an exemple :
![Screenshot 2022-12-01 at 18-08-12 length - CSS Cascading Style Sheets MDN](https://user-images.githubusercontent.com/19498121/205117913-d9092c32-f3f8-42ab-870f-94c792c201d5.png)
([https://developer.mozilla.org/en-US/docs/Web/CSS/length#browser_compatibility](url))

And since the browser's row is pretty big, it could be great to stick just the browser's icons on scroll, in my opinion.

**Comment by ferdnyc** [comment]
Agreed, it seems since December 2023 I've been using MDN with this userstyle applied (via the Stylus extension):

```css
@-moz-document domain("developer.mozilla.org") {
  figure.table-container {
    overflow: visible;
  }
  table.bc-table {
    position: relative;
  }
  table.bc-table thead {
    position: sticky;
    top: 97px;
    z-index: 500;
    background-color: var(--background-primary);
  }
}
```

It's an immense help on pages like https://developer.mozilla.org/en-US/docs/Web/API/Element where the BC table is **HUGE**.
