### DISCUSSION TITLE
How to reuse "Get changed files" in GitHub actions

### DISCUSSION THREAD

**Discussion by yin1999** [mdn/mdn-community#327] [Platform]
It's been a while since we migrated from tj-actions/changed-files to pure GitHub API calls to get changed files in PR (see mdn/translated-content#8952, mdn/content#21305...). And it works well and much more fast.

But it seems that we have made a lot copy of [this part](https://github.com/mdn/translated-content/blob/e9d090667639981ca677575d8e22ac913ce99d35/.github/workflows/pr-test.yml#L48-L64).

To improve maintainability, we'd better to make some changes to reuse this part, as mentioned by [@bsmth](https://github.com/mdn/translated-content/pull/4191#discussion_r1095532187) and [@nschonni](https://github.com/mdn/translated-content/pull/10390#issuecomment-1335674072).

After reading the [documation](https://docs.github.com/en/actions/using-workflows/reusing-workflows). We may have two solutions:

## reusable workflow

We could create reusable workflow in [workflow repo](https://github.com/mdn/workflows). And then we could reuse this like:

```yml
jobs:
  get-changed-files:
    uses: mdn/workflows/.github/workflows/list-changed-files.yml@main
    with:
      target-repo: "mdn/translated-content"
      paths: "^files/zh-cn/"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  some-job:
    runs-on: ubuntu-latest
    needs: get-changed-files
    if: ${{ needs.get-changed-files.outputs.files }}
    steps:
      # do sth.
```

This is a bit easy for us to create the workflow, but might be a bit difficult to use (with separated jobs).

## custom action

We could create a [custom action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action), this might be so of difficult (comparing with the reusable workflow). But we could use it like:

```yml
  steps:
    - name: Get changed files
      id: get-changed-files
      uses: mdn/list-changed-files@main
      with:
        # only list these paths
        paths: "^files/zh-cn/"
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: some-step
      if: ${{ steps.get-changed-files.outputs.files }}
      run: |
        # do sth.
```

could be as a step within a job

We'd better to make an appropriate decision on this :)
