### DISCUSSION TITLE
Blog post: How to draw any regular shape with just one JavaScript function

### DISCUSSION THREAD

**Discussion by dipikabh** [mdn/mdn-community#390] [Content]
Please leave your feedback and comments related to https://developer.mozilla.org/en-US/blog/javascript-shape-drawing-function/ here

**Comment by primeagen-rustaceans** [comment]
There is a typo in the article. Instead of 'Let's begin where I did with the hexagon and we'll take it from there.', I think it should be 'Let's begin with what I did with the hexagon and we'll take it from there.'. I wanted to rectify it by contributing to the same. But I am not able to find the article in the GitHub Repo.

**Reply by dipikabh** [reply]
Thanks for flagging the typo! This should get fixed shortly 👍 

Unfortunately, we are not accepting pull requests or issues for the blog (see this [announcement](https://github.com/orgs/mdn/discussions/379)). You're welcome to leave your thoughts and feedback in this discussion thread.

**Comment by mhsrio** [comment]
Thanks a ton for the wonderful blog. I really enjoyed reading and trying it on my own

**Comment by dmackerman** [comment]
Cool article. How about the source code that generated the image at the bottom? Would be good to use for inspiration.

**Comment by 9am** [comment]
Nice one! Thanks for sharing : ) 
Check out my **CSS version** with `@container`: https://codepen.io/9am/pen/bGQZpBp
</br>
<img width="50%" alt="shape" src="https://github.com/mdn/mdn-community/assets/1435457/f49d292c-fdd2-411c-9dcf-7f8c8ea8cf80">

```css
@container style(--side) {
    div {
        --r: 50%;
        --sl: calc(1turn / var(--side));
        clip-path: polygon(
            calc(var(--r) * (1 + cos(var(--sl) * 0))) calc(var(--r) * (1 + sin(var(--sl) * 0))),
            calc(var(--r) * (1 + cos(var(--sl) * 1))) calc(var(--r) * (1 + sin(var(--sl) * 1))),
            calc(var(--r) * (1 + cos(var(--sl) * 2))) calc(var(--r) * (1 + sin(var(--sl) * 2))),
            calc(var(--r) * (1 + cos(var(--sl) * 3))) calc(var(--r) * (1 + sin(var(--sl) * 3))),
            calc(var(--r) * (1 + cos(var(--sl) * 4))) calc(var(--r) * (1 + sin(var(--sl) * 4))),
            calc(var(--r) * (1 + cos(var(--sl) * 5))) calc(var(--r) * (1 + sin(var(--sl) * 5))),
            calc(var(--r) * (1 + cos(var(--sl) * 6))) calc(var(--r) * (1 + sin(var(--sl) * 6))),
            calc(var(--r) * (1 + cos(var(--sl) * 7))) calc(var(--r) * (1 + sin(var(--sl) * 7))),
            calc(var(--r) * (1 + cos(var(--sl) * 8))) calc(var(--r) * (1 + sin(var(--sl) * 8))),
            calc(var(--r) * (1 + cos(var(--sl) * 9))) calc(var(--r) * (1 + sin(var(--sl) * 9)))
        );
    }
}
```
