### DISCUSSION TITLE
Automated Prettier formatting on pull requests

### DISCUSSION THREAD

**Discussion by bsmth** [mdn/mdn-community#428] [Platform] [answered]
Hi all, I had promised to open a discussion about this topic, but I have only gotten around to it today, so my apologies for the delay.

After significant efforts to get all of our content Prettified (thanks to all who helped), we had some trouble with pull request checks, diagnosing and solving issues, particularly those opened by contributors via the GitHub UI. It's clear we need some additional tooling that will help us with those cases. In the meantime, we merged a pull request to disable Prettier checks in pull requests:

- [x] https://github.com/mdn/content/pull/27070

This is **temporary** while we get something in place to enforce the formatting requirements on incoming content without causing too much work for reviewers and authors. In the current state it's easier to automatically fix issues in content rather than troubleshoot broken CI. This is already handled in:

https://github.com/mdn/content/blob/3e2369d97e2d6fbfe33a3c496a8edd90e0b539e2/package.json#L17

We have a great suggestion from @queengooborg to try out a [GitHub action](https://github.com/marketplace/actions/prettier-action). This looks promising, but we will have to try it out.

Another option is a GitHub bot that reacts to `/commands` - I have a basic working demo of this that we can try, but it may be easier to use the action as we rely on this type of mechanism for everything else. If you think this is worth exploring (and possibly extending for other purposes), I can share the (horrible) code for this.

**Comment by yin1999** [comment]
Another way is provide code suggestions, I just found a project named [reviewdog](https://github.com/reviewdog/reviewdog#code-suggestions). It has provided a [tool](https://github.com/reviewdog/action-suggester) that just used for Github Action. An example here:

```yaml
      - name: Format changed content
        if: ${{ env.GIT_DIFF_CONTENT }}
        run: |
          yarn prettier --write ${{ env.GIT_DIFF_CONTENT }}
      - name: Submit suggestion
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: prettier
```

But this tool only handle `pull_request` event. I'm trying to create a GitHub action that could be triggered by some comment in PR just like '/prettier-suggestion' and could provide code suggestions (Just create the basic workflow [here](https://github.com/mdn/translated-content/commit/e04cf845a7f9c2e3a4730aae8642b2846b5a2b5e). I'm trying to figure out how to use reviewdog cli to submmit the code suggestions, but I'm a bit busy those days (: )
