### DISCUSSION TITLE
Evaluating size labels on PRs

### DISCUSSION THREAD

**Discussion by bsmth** [mdn/mdn-community#629] [Announcements]
Hi everyone 👋🏻 there's been a few requests for the team over the last few months to add `size` labels to pull requests, mainly for two reasons:

* help estimate the complexity of a PR before reviewers start (of which size is **one factor**)
* look over historical data or PRs over time to see the distribution of contribution size

We already have logic for labeling PRs by technology category based on file paths, so I have rolled it into the existing labeler workflow. Hopefully we will merge this shortly and see how it works for reviewers and contributors.

__Update (Jan 30th '24):__

Going with the following labels for `mdn/content` for now:

| Size  | LoC  |
|---|---|
| XS  | 0-5     |
| S   | 6-50     |
| M   | 51-500    |
| L   | 501-1000  |
| XL  | 1001+    |

- [x] Update PR: https://github.com/mdn/content/pull/31986

__Update:__ The labeler landed here:

- [x] https://github.com/mdn/content/pull/31758

__Criteria for size labels:__

I did not put too much thought into the size criteria for now, which initially looks like this:

```yml
          # Configuration for 'extra small' PRs
          xs_label: "size/xs"
          xs_max_size: "5"

          # Configuration for 'small' PRs
          s_label: "size/s"
          s_max_size: "10"

          
          # Configuration for 'medium' PRs
          m_label: "size/m"
          m_max_size: "50"

          # Configuration for 'large' PRs
          l_label: "size/l"
          l_max_size: "100"

          # 'Extra large' PRs are anything over `l_max_size` (>100 LoC)
          xl_label: "size/xl"
```

__Ignoring files:__

I have set the ignore list to the following:

```yml
          # List of files to exclude from size calculation
          # Files matching these patterns will not be considered when calculating PR size
          files_to_ignore: |
            "files/en-us/_redirects.txt"
            "files/en-us/_wikihistory.json"
```

If anyone has opinions or feedback on this, you're welcome to share. If you think other files should be ignored, the format of labels (`size/xs`, `size/s`, `size/m`, `size/l`, `size/xl`) or the label diff size is not good for each label (FYI, see [how k8s do it](https://github.com/kubernetes/kubernetes/labels?q=size)), feel free to share. 

Thanks a lot!
